"""Create tables

Revision ID: 6b091ded5393
Revises:
Create Date: 2023-02-18 19:03:13.275214

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6b091ded5393"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cat_colors_info",
        sa.Column(
            "color",
            sa.Enum("black", "white", "black & white", "red", "red & white", "red & black & white", name="cat_color"),
            nullable=False,
        ),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("color"),
        sa.UniqueConstraint("color"),
    )
    op.create_table(
        "cats",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "color",
            sa.Enum("black", "white", "black & white", "red", "red & white", "red & black & white", name="cat_color"),
            nullable=True,
        ),
        sa.Column("tail_length", sa.Integer(), nullable=True),
        sa.Column("whiskers_length", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "cats_stat",
        sa.Column("tail_length_mean", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("tail_length_median", sa.Numeric(), nullable=True),
        sa.Column("tail_length_mode", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("whiskers_length_mean", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("whiskers_length_median", sa.Numeric(), nullable=True),
        sa.Column("whiskers_length_mode", sa.ARRAY(sa.Integer()), nullable=True),
        sa.PrimaryKeyConstraint("tail_length_mean"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cats_stat")
    op.drop_table("cats")
    op.drop_table("cat_colors_info")
    # ### end Alembic commands ###
